import type { Bid, Quest, User } from "./types";

/**
 * Deterministic demo fixtures.
 *
 * Every person here is a single universal KAPAPI user. Nobody is "a GM" or
 * "a PLAYER" — those roles come from each QUEST's issuer/assignee/bidder edges.
 * `CURRENT_USER_ID` is deliberately the issuer of one QUEST, the assignee of
 * another and a pending bidder on a third, at the same time.
 */

export const CURRENT_USER_ID = "u-kim";

export const CATEGORIES: Record<string, string> = {
  cad: "도면 · CAD",
  image: "이미지 · 상세페이지",
  doc: "문서 · 자료 정리",
  data: "데이터 정리",
};

/** Display labels for skills, including sub-skills that are not QUEST categories. */
export const SKILL_LABELS: Record<string, string> = {
  ...CATEGORIES,
  dwg: "DWG 도면 작성",
};

export const USERS: Record<string, User> = {
  "u-kim": {
    id: "u-kim",
    name: "김도현",
    org: "한울건축사사무소",
    initials: "KD",
    skills: ["cad", "dwg", "doc"],
    credentials: ["건축기사"],
    clearances: ["NDA", "NO_PORTFOLIO_USE"],
    execution: {
      career: "건축사사무소 실무 5년 · 현황도/인허가 도면",
      careerYears: 5,
      questsComplete: 42,
      onTimeRate: 0.98,
      revisionRate: 0.04,
      disputes: 0,
      rating: 4.9,
      relevantHistory: { cad: 42, doc: 9 },
      availability: "AVAILABLE",
      level: 12,
      exp: 2860,
      expToNext: 3200,
    },
    issuer: {
      questsIssued: 6,
      paymentCompletionRate: 1,
      medianReviewHours: 3.2,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 4.8,
    },
  },
  "u-han": {
    id: "u-han",
    name: "한지우",
    org: "프리랜스 · 전 대형 건축사사무소",
    initials: "HJ",
    skills: ["cad", "dwg", "doc"],
    credentials: ["건축기사"],
    clearances: ["NDA", "NO_PORTFOLIO_USE"],
    execution: {
      career: "건축 CAD 8년 · 현황도/실시도면 정리",
      careerYears: 8,
      questsComplete: 156,
      onTimeRate: 0.99,
      revisionRate: 0.04,
      disputes: 0,
      rating: 4.9,
      relevantHistory: { cad: 47, doc: 12 },
      availability: "AVAILABLE",
      level: 24,
      exp: 8140,
      expToNext: 9000,
    },
    issuer: {
      questsIssued: 2,
      paymentCompletionRate: 1,
      medianReviewHours: 5.5,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 4.7,
    },
  },
  "u-seo": {
    id: "u-seo",
    name: "서준호",
    org: "프리랜스 · 설계사무소 3년",
    initials: "SJ",
    skills: ["cad", "dwg"],
    credentials: ["건축기사"],
    clearances: ["NDA"],
    execution: {
      career: "건축 설계 3년 · 야간 단기 작업 다수",
      careerYears: 3,
      questsComplete: 38,
      onTimeRate: 0.96,
      revisionRate: 0.09,
      disputes: 0,
      rating: 4.7,
      relevantHistory: { cad: 11 },
      availability: "AVAILABLE",
      level: 9,
      exp: 1740,
      expToNext: 2000,
    },
    issuer: {
      questsIssued: 0,
      paymentCompletionRate: 1,
      medianReviewHours: 0,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 0,
    },
  },
  "u-lee": {
    id: "u-lee",
    name: "이민재",
    org: "프리랜스 · 도면 보조 2년",
    initials: "LM",
    skills: ["cad"],
    credentials: [],
    clearances: ["NDA"],
    execution: {
      career: "건축/토목 도면 보조 2년",
      careerYears: 2,
      questsComplete: 22,
      onTimeRate: 0.94,
      revisionRate: 0.11,
      disputes: 0,
      rating: 4.4,
      relevantHistory: { cad: 8 },
      availability: "AVAILABLE",
      level: 6,
      exp: 900,
      expToNext: 1200,
    },
    issuer: {
      questsIssued: 0,
      paymentCompletionRate: 1,
      medianReviewHours: 0,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 0,
    },
  },
  "u-choi": {
    id: "u-choi",
    name: "최유나",
    org: "프리랜스 · CAD 4년",
    initials: "CY",
    skills: ["cad", "dwg"],
    credentials: [],
    /** No NDA posture on file — excluded by the security hard filter, not by identity. */
    clearances: [],
    execution: {
      career: "건축 CAD 4년",
      careerYears: 4,
      questsComplete: 51,
      onTimeRate: 0.97,
      revisionRate: 0.06,
      disputes: 0,
      rating: 4.8,
      relevantHistory: { cad: 19 },
      availability: "AVAILABLE",
      level: 14,
      exp: 3300,
      expToNext: 3600,
    },
    issuer: {
      questsIssued: 0,
      paymentCompletionRate: 1,
      medianReviewHours: 0,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 0,
    },
  },
  "u-yun": {
    id: "u-yun",
    name: "윤가람",
    org: "프리랜스 · 이커머스 비주얼",
    initials: "YG",
    skills: ["image", "doc"],
    credentials: [],
    clearances: ["NDA", "NO_PORTFOLIO_USE"],
    execution: {
      career: "이커머스 상세페이지·리터칭 6년",
      careerYears: 6,
      questsComplete: 211,
      onTimeRate: 0.97,
      revisionRate: 0.06,
      disputes: 0,
      rating: 4.8,
      relevantHistory: { image: 88, doc: 5 },
      availability: "AVAILABLE",
      level: 21,
      exp: 6420,
      expToNext: 7000,
    },
    issuer: {
      questsIssued: 1,
      paymentCompletionRate: 1,
      medianReviewHours: 8,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 4.6,
    },
  },
  "u-noh": {
    id: "u-noh",
    name: "노아린",
    org: "프리랜스 · 사진 보정 3년",
    initials: "NA",
    skills: ["image"],
    credentials: [],
    clearances: ["NDA"],
    execution: {
      career: "제품 사진 보정 3년",
      careerYears: 3,
      questsComplete: 76,
      onTimeRate: 0.93,
      revisionRate: 0.12,
      disputes: 1,
      rating: 4.4,
      relevantHistory: { image: 31 },
      availability: "AVAILABLE",
      level: 11,
      exp: 2210,
      expToNext: 2600,
    },
    issuer: {
      questsIssued: 0,
      paymentCompletionRate: 1,
      medianReviewHours: 0,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 0,
    },
  },
  "u-bae": {
    id: "u-bae",
    name: "배소윤",
    org: "프리랜스 · 편집디자인 8년",
    initials: "BS",
    skills: ["doc", "image"],
    credentials: [],
    clearances: ["NDA", "NO_PORTFOLIO_USE"],
    execution: {
      career: "편집디자인·기업 문서 정리 8년",
      careerYears: 8,
      questsComplete: 184,
      onTimeRate: 0.98,
      revisionRate: 0.05,
      disputes: 0,
      rating: 4.9,
      relevantHistory: { doc: 64, image: 22 },
      availability: "AVAILABLE",
      level: 22,
      exp: 7010,
      expToNext: 7600,
    },
    issuer: {
      questsIssued: 0,
      paymentCompletionRate: 1,
      medianReviewHours: 0,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 0,
    },
  },
  "u-im": {
    id: "u-im",
    name: "임채원",
    org: "프리랜스 · 데이터 정리 4년",
    initials: "IC",
    skills: ["doc", "data"],
    credentials: [],
    clearances: ["NDA"],
    execution: {
      career: "실측·현장 데이터 정리 4년",
      careerYears: 4,
      questsComplete: 129,
      onTimeRate: 0.95,
      revisionRate: 0.07,
      disputes: 0,
      rating: 4.6,
      relevantHistory: { data: 51, doc: 28 },
      availability: "LIMITED",
      level: 16,
      exp: 4120,
      expToNext: 4500,
    },
    issuer: {
      questsIssued: 0,
      paymentCompletionRate: 1,
      medianReviewHours: 0,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 0,
    },
  },
  "u-jung": {
    id: "u-jung",
    name: "정하윤",
    org: "서온건축사사무소",
    initials: "JH",
    skills: ["cad", "dwg"],
    credentials: ["건축사"],
    clearances: ["NDA", "NO_PORTFOLIO_USE"],
    execution: {
      career: "건축사 · 실무 11년",
      careerYears: 11,
      questsComplete: 3,
      onTimeRate: 1,
      revisionRate: 0,
      disputes: 0,
      rating: 5,
      relevantHistory: { cad: 3 },
      availability: "BUSY",
      level: 4,
      exp: 420,
      expToNext: 800,
    },
    issuer: {
      questsIssued: 14,
      paymentCompletionRate: 1,
      medianReviewHours: 2.1,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 4.9,
    },
  },
  "u-park": {
    id: "u-park",
    name: "박서진",
    org: "스튜디오 편 · 인테리어",
    initials: "PS",
    skills: ["image"],
    credentials: [],
    clearances: ["NDA"],
    execution: {
      career: "인테리어 시공 관리 7년",
      careerYears: 7,
      questsComplete: 1,
      onTimeRate: 1,
      revisionRate: 0,
      disputes: 0,
      rating: 5,
      relevantHistory: {},
      availability: "BUSY",
      level: 3,
      exp: 260,
      expToNext: 600,
    },
    issuer: {
      questsIssued: 9,
      paymentCompletionRate: 1,
      medianReviewHours: 6.4,
      cancellations: 1,
      disputes: 0,
      ratingFromPlayers: 4.6,
    },
  },
  "u-oh": {
    id: "u-oh",
    name: "오세림",
    org: "다온설계",
    initials: "OS",
    skills: ["doc"],
    credentials: [],
    clearances: ["NDA"],
    execution: {
      career: "설계사무소 관리 6년",
      careerYears: 6,
      questsComplete: 0,
      onTimeRate: 0,
      revisionRate: 0,
      disputes: 0,
      rating: 0,
      relevantHistory: {},
      availability: "BUSY",
      level: 2,
      exp: 120,
      expToNext: 400,
    },
    issuer: {
      questsIssued: 5,
      paymentCompletionRate: 1,
      medianReviewHours: 4.8,
      cancellations: 0,
      disputes: 0,
      ratingFromPlayers: 4.7,
    },
  },
};

const bid = (
  id: string,
  playerId: string,
  price: number,
  deliveryHours: number,
  arrivedAtMin: number,
  note?: string,
): Bid => ({ id, playerId, price, deliveryHours, arrivedAtMin, note });

/**
 * Flagship case (docs/PROTOTYPE_SPEC.md section 7).
 * Deadline is 6h and the ceiling is ₩180,000, so 이민재(12H) fails the deadline
 * filter and 최유나 fails the NDA filter. 한지우 and 서준호 both qualify, and
 * 한지우 wins on task history + reliability at a lower price — not on being
 * cheapest (이민재 was cheaper) and not on being fastest (서준호 was faster).
 */
export const FLAGSHIP_QUEST: Quest = {
  id: "0001",
  title: "손그림 현황 자료를 현황도 DWG로 정리",
  categoryId: "cad",
  categoryLabel: CATEGORIES.cad,
  summary:
    "실측 손그림과 현장 사진을 기준으로 A동 1층 현황도를 도면 레이어 규칙에 맞게 정리합니다.",
  issuerId: "u-jung",
  assigneeId: "u-han",
  state: "COMPLETE",
  createdAtLabel: "09-02 12:40",
  deadlineInHours: 6,
  deadlineLabel: "오늘 19:00",
  timeAttack: false,
  nda: true,
  budgetCeiling: 180000,
  rewardHint: [80000, 180000],
  requiredSkills: ["cad"],
  requiredCredentials: [],
  requiredClearances: ["NDA"],
  inputs: [
    { name: "현장실측_손그림_A동.jpg", kind: "JPG", size: "3.1 MB", note: "1층 평면 실측" },
    { name: "현장사진_11장.zip", kind: "ZIP", size: "22.4 MB" },
    { name: "레이어규칙_사내표준.pdf", kind: "PDF", size: "180 KB" },
  ],
  scope: [
    "A동 1층 현황 평면 1개 도면 작성",
    "벽체·개구부·계단·기둥 실측 치수 반영",
    "사내 레이어 규칙(레이어명·선종·색상) 준수",
    "치수선·실명·면적 표기",
  ],
  deliverables: ["A동 1층 현황도 1매"],
  outputFormats: ["DWG (AutoCAD 2018 이상)", "PDF (A2, 1:100)"],
  acceptanceCriteria: [
    "제출 형식 DWG + PDF 모두 포함",
    "레이어명이 사내 표준과 일치",
    "실측 치수와 도면 치수 불일치 없음",
  ],
  revisionBoundary: "합의된 범위 내 불일치에 대해 1회 수정",
  missingInfo: [],
  taskFit: { "u-han": 0.94, "u-seo": 0.86, "u-lee": 0.71, "u-choi": 0.88 },
  bids: [
    bid("b1", "u-lee", 80000, 12, 6, "야간 작업으로 진행 가능합니다."),
    bid("b2", "u-choi", 95000, 5, 11),
    bid("b3", "u-han", 110000, 6, 14, "동일 규칙 현황도 다수 정리했습니다."),
    bid("b4", "u-seo", 150000, 4, 21),
  ],
  events: [
    { at: "12:40", state: "OPEN", label: "QUEST 등록", detail: "QUEST #0001 CREATED" },
    { at: "12:46", state: "BIDDING", label: "입찰 4건 도착", detail: "4 BIDS RECEIVED" },
    { at: "13:01", state: "ROUTING", label: "KAPAPI 배정 검토", detail: "ROUTING" },
    { at: "13:02", state: "ASSIGNED", label: "작업자 배정", detail: "PLAYER ASSIGNED · 한지우" },
    { at: "13:08", state: "IN_PROGRESS", label: "작업 시작", detail: "WORK STARTED" },
    { at: "18:42", state: "DELIVERED", label: "결과 파일 도착", detail: "FILE DELIVERED" },
    { at: "18:51", state: "COMPLETE", label: "결과 확인 완료", detail: "QUEST COMPLETE" },
  ],
  result: {
    files: [
      { name: "A동_1층_현황도.dwg", kind: "DWG", size: "1.8 MB" },
      { name: "A동_1층_현황도.pdf", kind: "PDF", size: "740 KB" },
    ],
    deliveredAt: "18:42",
    minutesVsDeadline: 18,
    checks: [
      { label: "파일 수신", passed: true },
      { label: "요청 형식(DWG·PDF) 포함", passed: true },
      { label: "납품 시각 기록", passed: true },
    ],
  },
};

const questsList: Quest[] = [
  FLAGSHIP_QUEST,
  {
    id: "0182",
    title: "쇼핑몰 상세페이지 12종 이미지 정리",
    categoryId: "image",
    categoryLabel: CATEGORIES.image,
    summary:
      "촬영 원본 12종을 상세페이지 규격에 맞게 배경 정리·리사이즈하고 파일명을 통일합니다.",
    issuerId: CURRENT_USER_ID,
    assigneeId: "u-yun",
    state: "COMPLETE",
    createdAtLabel: "08-28 10:12",
    deadlineInHours: 6,
    deadlineLabel: "08-28 17:00",
    timeAttack: false,
    nda: true,
    budgetCeiling: 140000,
    rewardHint: [90000, 140000],
    requiredSkills: ["image"],
    requiredCredentials: [],
    requiredClearances: ["NDA"],
    inputs: [{ name: "촬영원본_12종.zip", kind: "ZIP", size: "184 MB" }],
    scope: [
      "이미지 12종 배경 정리",
      "상세페이지 규격 860px 폭 리사이즈",
      "파일명 규칙 적용",
    ],
    deliverables: ["정리 이미지 12종"],
    outputFormats: ["JPG", "PNG"],
    acceptanceCriteria: ["12종 모두 포함", "규격 폭 860px 일치"],
    revisionBoundary: "규격 불일치에 대해 1회 수정",
    missingInfo: [],
    taskFit: { "u-yun": 0.93, "u-noh": 0.8, "u-bae": 0.76 },
    bids: [
      // u-noh is the cheapest and still loses: 8H misses a 6H deadline.
      bid("c1", "u-noh", 96000, 8, 9),
      bid("c2", "u-yun", 118000, 5, 17),
      bid("c3", "u-bae", 132000, 6, 24),
      // u-im has no image work on file — filtered on skills, not on identity.
      bid("c4", "u-im", 104000, 5, 31),
    ],
    events: [
      { at: "10:12", state: "OPEN", label: "QUEST 등록", detail: "QUEST #0182 CREATED" },
      { at: "10:31", state: "ROUTING", label: "KAPAPI 배정 검토", detail: "ROUTING" },
      { at: "10:32", state: "ASSIGNED", label: "작업자 배정", detail: "PLAYER ASSIGNED · 윤가람" },
      { at: "15:24", state: "DELIVERED", label: "결과 파일 도착", detail: "FILE DELIVERED" },
      { at: "15:39", state: "COMPLETE", label: "결과 확인 완료", detail: "QUEST COMPLETE" },
    ],
    result: {
      files: [{ name: "상세페이지_정리본_12종.zip", kind: "ZIP", size: "41 MB" }],
      deliveredAt: "15:24",
      minutesVsDeadline: 96,
      checks: [
        { label: "파일 수신", passed: true },
        { label: "이미지 12종 개수 확인", passed: true },
        { label: "납품 시각 기록", passed: true },
      ],
    },
  },
  {
    id: "0201",
    title: "인테리어 실측 도면을 평면도로 정리",
    categoryId: "cad",
    categoryLabel: CATEGORIES.cad,
    summary:
      "현장 실측 스케치를 기준으로 30평 주거 평면도를 정리합니다. 가구 배치는 제외합니다.",
    issuerId: "u-park",
    state: "BIDDING",
    createdAtLabel: "오늘 09:40",
    deadlineInHours: 20,
    deadlineLabel: "내일 09:00",
    timeAttack: false,
    nda: true,
    budgetCeiling: 160000,
    rewardHint: [90000, 160000],
    requiredSkills: ["cad"],
    requiredCredentials: [],
    requiredClearances: ["NDA"],
    inputs: [
      { name: "실측스케치_301호.pdf", kind: "PDF", size: "2.2 MB" },
      { name: "현장사진_6장.zip", kind: "ZIP", size: "12.8 MB" },
    ],
    scope: ["30평 주거 평면 1개 도면", "벽체·개구부 실측 반영", "가구 배치 제외"],
    deliverables: ["평면도 1매"],
    outputFormats: ["DWG", "PDF"],
    acceptanceCriteria: ["DWG·PDF 모두 포함", "실측 치수 반영"],
    revisionBoundary: "범위 내 불일치 1회 수정",
    missingInfo: [],
    taskFit: { "u-kim": 0.9, "u-seo": 0.84, "u-lee": 0.7 },
    bids: [
      bid("d1", "u-lee", 88000, 16, 12),
      bid("d2", "u-kim", 120000, 10, 26, "동일 규모 현황도 다수 진행했습니다."),
      bid("d3", "u-seo", 138000, 8, 33),
    ],
    events: [
      { at: "09:40", state: "OPEN", label: "QUEST 등록", detail: "QUEST #0201 CREATED" },
      { at: "10:06", state: "BIDDING", label: "입찰 3건 도착", detail: "3 BIDS RECEIVED" },
    ],
  },
  {
    id: "0207",
    title: "인허가 제출 도면 표제란·축척 정리",
    categoryId: "cad",
    categoryLabel: CATEGORIES.cad,
    summary:
      "제출용 도면 9매의 표제란 항목과 출력 축척을 제출 규격에 맞게 통일합니다.",
    issuerId: "u-oh",
    assigneeId: CURRENT_USER_ID,
    state: "IN_PROGRESS",
    createdAtLabel: "오늘 08:15",
    deadlineInHours: 9,
    deadlineLabel: "오늘 21:00",
    timeAttack: false,
    nda: true,
    budgetCeiling: 150000,
    requiredSkills: ["cad"],
    requiredCredentials: [],
    requiredClearances: ["NDA"],
    inputs: [{ name: "제출도면_9매.zip", kind: "ZIP", size: "34 MB" }],
    scope: ["도면 9매 표제란 항목 통일", "출력 축척 1:100 고정", "도면번호 재정렬"],
    deliverables: ["정리 도면 9매"],
    outputFormats: ["DWG", "PDF"],
    acceptanceCriteria: ["9매 모두 포함", "표제란 항목 누락 없음"],
    revisionBoundary: "범위 내 불일치 1회 수정",
    missingInfo: [],
    taskFit: { "u-kim": 0.92, "u-seo": 0.81 },
    bids: [
      bid("e1", "u-seo", 105000, 8, 14),
      bid("e2", "u-kim", 112000, 6, 19),
    ],
    events: [
      { at: "08:15", state: "OPEN", label: "QUEST 등록", detail: "QUEST #0207 CREATED" },
      { at: "08:44", state: "ROUTING", label: "KAPAPI 배정 검토", detail: "ROUTING" },
      { at: "08:45", state: "ASSIGNED", label: "작업자 배정", detail: "PLAYER ASSIGNED · 김도현" },
      { at: "09:02", state: "IN_PROGRESS", label: "작업 시작", detail: "WORK STARTED" },
    ],
  },
  {
    id: "0211",
    title: "제품 상세 이미지 24종 배경 제거·리사이즈",
    categoryId: "image",
    categoryLabel: CATEGORIES.image,
    summary: "신제품 촬영본 24종의 배경을 제거하고 스토어 규격으로 리사이즈합니다.",
    issuerId: "u-park",
    state: "BIDDING",
    createdAtLabel: "오늘 14:20",
    deadlineInHours: 4,
    deadlineLabel: "오늘 20:00",
    timeAttack: true,
    nda: false,
    budgetCeiling: 130000,
    rewardHint: [80000, 130000],
    requiredSkills: ["image"],
    requiredCredentials: [],
    requiredClearances: [],
    inputs: [{ name: "신제품_촬영본_24종.zip", kind: "ZIP", size: "312 MB" }],
    scope: ["이미지 24종 배경 제거", "1000×1000 정사각 리사이즈", "파일명 SKU 규칙 적용"],
    deliverables: ["정리 이미지 24종"],
    outputFormats: ["PNG"],
    acceptanceCriteria: ["24종 모두 포함", "규격 1000×1000 일치"],
    revisionBoundary: "규격 불일치 1회 수정",
    missingInfo: [],
    taskFit: { "u-yun": 0.91, "u-noh": 0.83, "u-bae": 0.72 },
    bids: [
      bid("f1", "u-noh", 84000, 4, 5),
      bid("f2", "u-bae", 99000, 3, 11),
      bid("f3", "u-yun", 106000, 3, 16),
      bid("f4", "u-im", 92000, 4, 22),
      bid("f5", "u-seo", 88000, 4, 27),
    ],
    events: [
      { at: "14:20", state: "OPEN", label: "QUEST 등록", detail: "QUEST #0211 CREATED" },
      { at: "14:33", state: "BIDDING", label: "입찰 5건 도착", detail: "5 BIDS RECEIVED" },
    ],
  },
  {
    id: "0214",
    title: "회사소개서 PPT 32p 레이아웃 정리",
    categoryId: "doc",
    categoryLabel: CATEGORIES.doc,
    summary: "기존 32페이지 소개서의 서식·정렬·폰트를 사내 템플릿에 맞게 통일합니다.",
    issuerId: "u-oh",
    state: "BIDDING",
    createdAtLabel: "오늘 11:05",
    deadlineInHours: 26,
    deadlineLabel: "내일 15:00",
    timeAttack: false,
    nda: true,
    budgetCeiling: 180000,
    rewardHint: [110000, 180000],
    requiredSkills: ["doc"],
    requiredCredentials: [],
    requiredClearances: ["NDA"],
    inputs: [
      { name: "회사소개서_v7.pptx", kind: "PPTX", size: "18 MB" },
      { name: "사내템플릿.potx", kind: "POTX", size: "1.2 MB" },
    ],
    scope: ["32페이지 서식 통일", "표·차트 정렬 정리", "폰트 사내 표준 적용"],
    deliverables: ["정리본 PPTX 1개"],
    outputFormats: ["PPTX", "PDF"],
    acceptanceCriteria: ["32페이지 모두 포함", "템플릿 폰트 적용"],
    revisionBoundary: "서식 불일치 1회 수정",
    missingInfo: [],
    taskFit: { "u-bae": 0.9, "u-im": 0.78, "u-yun": 0.7, "u-kim": 0.62 },
    bids: [
      bid("g1", "u-im", 124000, 20, 18),
      bid("g2", "u-bae", 146000, 14, 25),
    ],
    events: [
      { at: "11:05", state: "OPEN", label: "QUEST 등록", detail: "QUEST #0214 CREATED" },
      { at: "11:44", state: "BIDDING", label: "입찰 2건 도착", detail: "2 BIDS RECEIVED" },
    ],
  },
  {
    id: "0216",
    title: "현장 실측 데이터 스프레드시트 정리",
    categoryId: "data",
    categoryLabel: CATEGORIES.data,
    summary: "현장에서 수기로 기록한 실측값 420행을 정해진 컬럼 구조로 정리합니다.",
    issuerId: "u-jung",
    state: "OPEN",
    createdAtLabel: "오늘 15:02",
    deadlineInHours: 30,
    deadlineLabel: "내일 21:00",
    timeAttack: false,
    nda: true,
    budgetCeiling: 90000,
    rewardHint: [50000, 90000],
    requiredSkills: ["data"],
    requiredCredentials: [],
    requiredClearances: ["NDA"],
    inputs: [{ name: "실측기록_스캔.pdf", kind: "PDF", size: "9.4 MB" }],
    scope: ["420행 데이터 입력", "지정 컬럼 구조 적용", "중복·공백 정리"],
    deliverables: ["정리 스프레드시트 1개"],
    outputFormats: ["XLSX", "CSV"],
    acceptanceCriteria: ["420행 모두 입력", "컬럼 구조 일치"],
    revisionBoundary: "입력 오류 1회 수정",
    missingInfo: [],
    taskFit: { "u-im": 0.89 },
    bids: [],
    events: [
      { at: "15:02", state: "OPEN", label: "QUEST 등록", detail: "QUEST #0216 CREATED" },
    ],
  },
];

export const QUESTS: Record<string, Quest> = Object.fromEntries(
  questsList.map((q) => [q.id, q]),
);

export const QUEST_IDS = questsList.map((q) => q.id);

/**
 * BIDs that arrive on a newly created QUEST, chosen by category so the supply
 * side stays credible whatever the visitor types. Deterministic by construction.
 */
export function bidsForCategory(categoryId: string): Bid[] {
  switch (categoryId) {
    case "cad":
      return [
        bid("n1", "u-lee", 92000, 14, 4),
        bid("n2", "u-choi", 104000, 7, 9),
        bid("n3", "u-han", 128000, 6, 13, "동일 유형 도면 정리 경험이 많습니다."),
        bid("n4", "u-seo", 155000, 5, 19),
      ];
    case "image":
      return [
        bid("n1", "u-noh", 88000, 9, 5),
        bid("n2", "u-bae", 112000, 7, 10),
        bid("n3", "u-yun", 124000, 5, 14, "상세페이지 규격 작업 다수 진행했습니다."),
        bid("n4", "u-im", 98000, 11, 21),
      ];
    case "data":
      return [
        bid("n1", "u-im", 76000, 10, 6),
        bid("n2", "u-bae", 105000, 8, 12),
        bid("n3", "u-noh", 69000, 22, 18),
      ];
    default:
      return [
        bid("n1", "u-im", 96000, 12, 5),
        bid("n2", "u-yun", 118000, 9, 11),
        bid("n3", "u-bae", 134000, 7, 15, "사내 템플릿 기준 정리 작업을 자주 합니다."),
        bid("n4", "u-noh", 88000, 18, 23),
      ];
  }
}

export function taskFitForCategory(categoryId: string): Record<string, number> {
  switch (categoryId) {
    case "cad":
      return { "u-han": 0.93, "u-seo": 0.85, "u-lee": 0.72, "u-choi": 0.87 };
    case "image":
      return { "u-yun": 0.92, "u-noh": 0.81, "u-bae": 0.75, "u-im": 0.6 };
    case "data":
      return { "u-im": 0.9, "u-bae": 0.72, "u-noh": 0.55 };
    default:
      return { "u-bae": 0.89, "u-im": 0.79, "u-yun": 0.71, "u-noh": 0.58 };
  }
}
